#include <windows.h>
#include "struct.h"
                                                      

                                                      
                                                      
struct SComplexe
{
	float Re;
	float Im;
};
                                                      

 void  FFT2D(SImage imS,SImage imModule,SImage imPhase);
 long  puissance2(long p);   
 long  TestPuissance2(long valeur);
