//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by winseg2005.rc
//
#define IDS_STRING1                     1
#define IDR_IMAGE                       101
#define IDR_MAINFRAME                   102
#define ID_IMAGE                        103
#define ID_EXIT                         104
#define IDB_SPLASH                      105
#define CG_IDD_PROGRESS                 106
#define ID_INDICATOR_DATE               107
#define ID_FILE_EXIT                    108
#define ID_INDICATOR_TIME               109
#define CG_IDD_MYDIALOGBAR              110
#define ID_TRAITEMENT                   111
#define ID_SAUVER                       113
#define ID_INVERSION_VIDEO              114
#define IDI_ICON1                       114
#define IDI_LE2I                        114
#define AFX_IDI_STD_MDIFRAME1           115
#define IDD_DIALOG1                     115
#define IDD_ZONE                        115
#define IDR_PALETTE                     116
#define IDR_HISTO                       117
#define IDR_COUPE                       118
#define ID_GRAB                         118
#define ID_SNAP                         119
#define IDR_IMAGE2                      119
#define IDR_IMAGE1                      119
#define IDR_ACQIMAGENB                  119
#define ID_FREEZE                       120
#define IDD_SEUIL                       120
#define IDR_COLOR                       120
#define IDD_CARAC_ZONE                  121
#define ID_ZONE                         122
#define IDD_LIMITE_SEQUENCE             122
#define ID_RESTAURE                     123
#define IDD_DOUBLESEUIL                 123
#define ID_CLOSE                        124
#define IDD_DOUBLESEUIL1                124
#define IDD_SEUIL2                      124
#define ID_NB                           125
#define IDD_LISTE                       125
#define ID_COULEUR                      126
#define IDD_NBAPP                       126
#define ID_AFFICHE_PALETTE              127
#define IDI_ICON2                       127
#define IDD_PARAM                       127
#define ID_SEUILLAGE                    128
#define ID_RESTAURE_PALETTE             129
#define IDR_ACQIMAGECOLOR               129
#define IDD_INSTALL                     129
#define ID_CLOSE_PALETTE                130
#define IDD_LARGHAUT                    131
#define IDD_DIALOG2                     132
#define IDD_PALETTE                     132
#define IDD_LHFLOAT                     133
#define IDR_FLOAT                       133
#define ID_INFORMATION_COUPE            134
#define IDD_ECHELLE                     134
#define IDD_Hysteresis                  136
#define IDD_SetT                        137
#define ID_INFO_GENERALE                138
#define ID_SEUILLER_IMAGE               139
#define IDR_VUE3D                       140
#define ID_FONCTION_REPARTITION         141
#define ID_HISTOGRAMME                  142
#define ID_HORIZONTALE                  145
#define ID_VERTICALE                    146
#define ID_OBLIQUE                      147
#define IDD_DIALVAL                     149
#define ID_HISTO_OPTIONS_CURSEUR        150
#define IDD_DIAL2VAL                    150
#define ID_COUPE_SAUVER                 151
#define IDD_CONFIGAPP                   151
#define ID_COUPE_EXIT                   152
#define IDD_CONFIGDEC                   152
#define IDR_MESPOL                      152
#define ID_COUPE_OPTIONS_CURSEUR        153
#define ID_COUPE_OPTIONS_LISSAGE1       154
#define ID_COUPE_OPTIONS_LISSAGE2       155
#define IDR_TOOLBAR2                    155
#define ID_HISTO_SAUVER                 156
#define ID_HISTO_EXIT                   157
#define IDD_DIALOG_HOUGH                157
#define ID_SEUIL2                       158
#define IDD_DIALOG_AMIN_SEUIL           158
#define ID_ZONE_MANUELLE                159
#define ID_INFORMATION                  159
#define IDI_BMP                         159
#define ID_MIROIR_VERT                  160
#define IDI_F32                         160
#define ID_MIROIR_HORI                  161
#define IDD_DIALOG_OPERATION            161
#define IDD_DIALPARZ                    161
#define ID_SEQUENCE                     162
#define ID_LIRE_SEQUENCE                163
#define ID_SAUVE_SEQUENCE               164
#define IDI_MEM                         164
#define ID_CREER_SEQUENCE               165
#define ID_DETRUIRE_SEQUENCE            166
#define IDD_DIALRELIEF                  166
#define ID_ROBERTS                      167
#define IDD_PROJET_APPR                 167
#define ID_PREWITT                      168
#define ID_RESTAURE_IMAGE               169
#define ID_SEUILLAGE2                   170
#define IDD_FACTEUR_ZOOM                170
#define ID_SEUILLAGE1                   171
#define IDD_INFO_TRAITEMENT             171
#define IDD_DIALOG3                     172
#define ID_FFT                          173
#define IDD_CONFIGPOLY                  173
#define IDB_BITMAPTREE                  176
#define ID_ETIQUETTAGE                  177
#define ID_SEGMENTATION_DCISION         178
#define ID_ROTATIONS_GAUCHE             179
#define IDD_NBPOINTAPPR                 179
#define ID_ROTATIONS_DROITE             180
#define IDD_PMC                         180
#define ID_COLOR                        181
#define IDD_CONFIDEC                    181
#define ID_SOBEL                        182
#define IDD_CHOIXCLASS                  182
#define ID_SEGMENTATION_CALCULDESPARAMTRES 183
#define ID_LUMCHRO                      184
#define ID_SEGMENTATION_POLYTOPES       184
#define ID_CHROMINANCE                  185
#define IDD_LEGENDE                     185
#define ID_ConfigDecision               187
#define ID_ZOOM_100                     188
#define ID_ZOOM_50                      189
#define ID_ZOOM_25                      190
#define ID_PROFIL                       191
#define ID_SEGMENTATION_APPRENTISSAGEGLOBAL 191
#define ID_SEGMENTATION_OPTIMISATIONMES 192
#define ID_SEGMENTATION_OPTIMISATIONPOLYTOPES 193
#define ID_IMAGEVIDE                    194
#define IDD_DIALSEQ                     194
#define ID_MIN_MAX_AUTO                 195
#define ID_ConfigApp                    195
#define IDD_DIALMORPHO                  195
#define ID_IMAGEFLOAT                   196
#define ID_HAAR                         197
#define ID_BSPLINE                      198
#define IDC_RECT                        198
#define ID_RECONSTRUCT                  199
#define ID_CONT                         200
#define ID_FICHIER_QUITTER              200
#define ID_VISUALISATION_CHOIXDESPARAMETRES 201
#define IDR_GRAPH                       201
#define ID_SOUS_ECHAN_LIGNE             202
#define ID_SOUS_ECHAN_COL               203
#define ID_VISUALISATION_INFOPOLYTOPES  203
#define IDD_DIALOG_CURVI                203
#define ID_OUVRIR_IM_BYTE               204
#define ID_VISUALISATION_INFOMESURES    204
#define IDC_CURSOR1                     204
#define ID_FERMER_PALETTE               205
#define ID_SEGMENTATION_DECISIONSANS    205
#define ID_EXEMPLE                      206
#define IDD_DIALOG_COUPECURVI           206
#define ID_IMAGEFLOAT_TO_BYTE           207
#define IDD_BoiteParamCurviDetect       207
#define ID_IMAGEFLOAT_TO_FLOAT          208
#define IDD_DIALOG_PARAMAFFINE          208
#define ID_TRAITEMENT_SUPPRIMER         209
#define IDD_DIALOG_PROGRESSCURVI        209
#define ID_AFFECTER_ECHELLE             210
#define ID_TRAITEMENT_LUMINANCEMOYENNESEUIL 211
#define ID_FICHIER_OUVRIRLUTEXCEL       213
#define ID_MULTI_ECHELLE                214
#define ID_APPLIHERVE_VECTEURTRANSLATION_VISUCOORDONNEES 215
#define ID_PARAMTRAGE_VISUALISATIONMESOUPOL 215
#define ID_NORMALISATION                216
#define ID_APPLIHERVE_BRUIT_VISUALISERBRUIT 217
#define ID_COPIE_EN_FLOAT               217
#define ID_WINDOW_CLOSEGRAPHICS         217
#define ID_APPLIHERVE_LUT_CHARGERLUT    218
#define IDC_COMMENTAIRES                218
#define ID_COPIE_EN_BYTE                218
#define ID_APPLIHERVE_LUT_VISUALISERLUT 219
#define ID_MASQUE_RECHERCHER            219
#define ID_APPLIHERVE_IMAGERSULTAT      220
#define ID_MASQUE_ANNULER               220
#define ID_GRAD_ROBERTS                 222
#define ID_OP_PREWITT                   223
#define ID_EDIT_TOOLBAR                 224
#define ID_CONTOUR_SEUILLAGE1HYSTERESIS 225
#define ID_IMAGE_STATUS_BAR             226
#define ID_CONTOUR_SEUILLAGE2HYSTERESIS 226
#define ID_LAPLACIEN1                   226
#define ID_LAPLACIEN_2                  227
#define ID__MOYENNEURXY111              228
#define ID_MOYENNEURX111                229
#define ID_MOYENNEURY111                230
#define ID_MOYENNEURXY121               231
#define ID_FILTREGAUSSIEN               232
#define ID_ECHANT_LIGNE_COL             232
#define ID_FILTRE_EXPONENTIEL           233
#define ID_PARZEN                       233
#define ID_ORDRE_MEDIAN                 234
#define ID_ORDRE_MILIEU                 235
#define ID_MORPHO_OUVERTURE             236
#define ID_BASSE                        236
#define ID_PARZEN_CALCULDETOUS          236
#define ID_MORPHO_FERMETURE             237
#define ID_MASQUE_LAMAIN                237
#define ID_MORPHO_EROSION               238
#define ID_MORPHO_DILATATION            239
#define ID_MISE_A_ZERO                  239
#define ID_CONTOURS_CONTOURHYSTRSIS2    240
#define ID_CONTOURS_CONTOURHYSTRSISFEN88 242
#define ID_MASQUE_NBPIXELS              243
#define ID_MASQUE_CALCULSLOCAUX_CONTRASTE 245
#define ID_MASQUE_CALCULSLOCAUX_MAXMIN  246
#define ID_MASQUE_CALCULSLOCAUX_ENTROPIE 247
#define ID_ABOUT                        248
#define ID_MASQUE_CALCULSLOCAUX_LUMINANCEMOYENNE 248
#define ID_MASQUE_CALCULSLOCAUX_GRADIENTMOYEN 249
#define ID_MASQUE_CALCULSLOCAUX_TOUS    250
#define ID_TRAITEMENT_FILTRESETT        255
#define ID_TRAITEMENT_FILTRESSETT_FILTRESETTNONNORMALIS 256
#define ID_OUTILS_VUE3D                 257
#define ID_EDITION_255                  258
#define ID_EDIT_TOOLVPS                 259
#define ID_TRAITEMENT_REDUCTIONSUR16NIVEAUX 259
#define ID_INFO_IMAGE                   260
#define ID_CONTOUR_SEUILLAGE3HYSTERESIS 261
#define ID_DST                          261
#define ID_SOMMET_GALET                 262
#define ID_TRAITEMENT_SOBEL             262
#define ID_TRAITEMENT_CORRELATION       263
#define ID_COUPE_STATUS_BAR             264
#define ID_TH_DROITE                    265
#define ID_SAUVE_EXCEL                  266
#define ID_ETIQUETTAGE_MAX              267
#define ID_ETIQUETTAGE_CG               268
#define ID_AMINC_VERTI_BIDIRECT         271
#define ID_AMINCISSEMENT                272
#define ID_ETIQUET_CG_NG                273
#define ID_IMAGE_GEO                    274
#define ID_TH_DROITE_1AM                275
#define ID_TH_DROITE_MA1                276
#define ID_IMAGE_TEST                   280
#define ID_TRAITEMENT_LUMINANCEMOYENNE  280
#define ID_BRUIT_IMPULSIONNEL           281
#define ID_MASQUE_ESSAI                 281
#define ID_BRUIT_GAUSSIEN               282
#define ID_BRUIT_EXPONENTIEL            283
#define ID_BRUIT_UNIFORME               284
#define ID_BRUIT_POISSON                285
#define ID_BRUIT_RAYLEIGH               286
#define ID_ADDITION_IMAGES              287
#define ID_ADDITION_IMAGE               288
#define ID_DIVISION_IMAGE               289
#define ID_SOUSTRACTION_IMAGE           290
#define ID_TRAITEMENT_FILTRESSETT_HAUTBAS 292
#define ID_TH_NORM_1AM                  293
#define ID_MASQUE_ESSAI2                293
#define ID_TH_NORMMA1                   294
#define ID_MASQUE_ESSAI3                294
#define ID_MASQUE_ESSAI4                296
#define ID_MASQUE_ESSAI5                297
#define ID_ZOOM_X                       298
#define ID_SPLINE_FLOAT                 301
#define ID_EXTRA_PAUL                   302
#define ID_HAAR_FLOAT                   303
#define ID_SAUVER_SOUS                  304
#define ID_TEST                         305
#define ID_VISUALISATION_VISUALISERLESPOLYTOPES 305
#define ID_CONTOURS_CONTOURHYSTRSIS1    306
#define ID_TRAITEMENT_MODIFICATIONDHISTOGRAMME_EXPANSIONDYNAMIQUE 307
#define ID_CORRELATION_CALCUL           308
#define ID_PARAMTRAGE_VISUALISATIONPARAMTRES 308
#define ID_CORRELATION_CALCULDANS       309
#define ID_PARAMTRAGE_PARAMTRES         309
#define ID_MASQUE_CONTRASTE             310
#define ID_MASQUE_MAXMIN                311
#define ID_MASQUE_ENTROPIE              312
#define ID_MASQUE_LUMINANCEMOYENNE      313
#define ID_MASQUE_GRADIENTMOYEN         314
#define ID_VISUALISATION_TOOLBAR        315
#define ID_MASQUE_DIMENSIONS            315
#define ID_MASQUE_TOUS                  316
#define ID_MASQUE_HISTOGRAMME           317
#define ID_MASQUE_ESSAI6                318
#define ID_MASQUE_LOCAUXCONTRASTE       319
#define ID_SEGMENTATION_AJOUTERBASEMESUNFICHIERMES 320
#define ID_TRAITEMENT_GRADIENTDEROB     321
#define ID_MASQUE_DCOUPAGE              322
#define ID_TRAITEMENT_MODIFICATIONDHISTOGRAMME_EGALISATIONDHISTOGRAMME 323
#define ID_TRAITEMENT_MAXMIN            324
#define ID_MASQUE_5PARAMTRES            325
#define ID_SEGMENTATION_DFINIRUNEVALEURDER 326
#define ID_SEGMENTATION_POLYTOPESMULTICLASSES_OUVRIRUNFICHIERMC 327
#define ID_SEGMENTATION_POLYTOPESMULTICLASSES_AJOUTERUNECLASSE 328
#define ID_SEGMENTATION_POLYTOPESMULTICLASSES_GNRERLE 329
#define ID_SEGMENTATION_POLYTOPESMULTICLASSES_DCISION 330
#define ID_SEGMENTATION_POLYTOPESMULTICLASSES_DCISION3PARAM 331
#define ID_ACQURIR_SQUENCE_3AQUISITIONSQUENCECALCUL 332
#define ID_ACQUI_SEQUENCE               333
#define ID_APPRENTISSAGE_GNRERUNPROJET  341
#define ID_APPRENTISSAGE_DFINIRLESPARAMTRES 342
#define ID_CALCUL_TEXTURE               343
#define ID_APPRENTISSAGE_CONSTRUIRELEFICHIERMULTICLASSES 344
#define ID_APPRENTISSAGE_GNRERLEFICHIERDAPPRENTISSAGE 345
#define ID_APPRENTISSAGE_GNRERUNFICHIERPOLYTOPESMULTICLASSES 347
#define ID_DCISION_CONFIGURATIONDELADCISION 350
#define ID_DCISION_DCISION              351
#define ID_DCISION_DCISIONAVECMASQUE    352
#define ID_VISUALISATION_CHOIXDUNFICHIERDEPOLYTOPES 353
#define ID_CALCULS_CHOIXDECLASSES       354
#define ID_CARACTECLAIR                 356
#define ID_MASQUE_CARACTRISATIONGLOBAL  357
#define ID_DCISION_DCISION2MASQUES      361
#define ID_TRAITEMENT_SOUSTRACTION      363
#define ID_MASQUE_MASQUEFIXE            365
#define ID_TRAITEMENT_MAX121232B        366
#define ID_TRAITEMENT_TESTCONTRATSE     367
#define ID_TRAITEMENT_5PARAMTRESCOMMUN  368
#define ID_TRAITEMENT_5PARAMTRESETESSAIS_5PARAMTRESCOMMUNMASQUE 369
#define ID_TEST2                        372
#define ID_TRAITEMENT_5PARAMTRESETESSAIS_ESSAITOT 373
#define ID_TRAITEMENT_RECALAGE          374
#define ID_CALCULELLIPSE                375
#define ID_DCISION_DCISION3MASQUES      376
#define ID_DCISION_DECISION3MASQUESENREGIST 378
#define ID_DCISION_DCISION3MASQUESADAPT 380
#define ID_TRAITEMENT_CENTRE            381
#define ID_DCISION_DCISION3MASQUESCG    382
#define ID_DCISION_DCISION3MASQUESSANSRECH 383
#define ID_TRAITEMENT_DESSINMESURES     384
#define ID_ACQURIR_RGLAGES              385
#define ID_DCISION_DECISIONPARZENCIRCULARIT 388
#define ID_PARZEN3D_CALCULDESESPACESDEPROBA 392
#define ID_PARZEN3D_CRERUNESPACEDEDCISION 393
#define ID_PARZEN3D_OUVRIRUNESPACEDEDCISION 394
#define ID_PARZEN3D_SAUVEGARDERUNESPACEDEDCISION 395
#define ID_PARZEN3D_VISUALISERLESPACEDEDCISION 396
#define ID_DCISION_PARZEN_DCISIONENREGISTRE 397
#define ID_MASQUE_INVERSION             398
#define ID_DCISION_TEST                 401
#define ID_DCISION_REMPLISSAGEDELESPACEDESPARAM 402
#define ID_DCISION_REMPLISSAGEDELESPDESPARAMSEQ 403
#define ID_DCISION_TESTPROB             405
#define ID_TRAITEMENT_RDUCTIONDENIVEAUX 406
#define ID_DCISION_PARZEN_IMAGECOMPLTE  407
#define ID_OPTIONS_ZOOM                 408
#define ID_PARZEN3D_MESRURERECOUVREMENTSAVECCL0 413
#define ID_TRAITEMENT_CORRELATION_CORRELATION2 414
#define ID_TRAITEMENT_CODAGEEXTREMA     418
#define ID_TRAITEMENT_DENSITDANSZONE    419
#define ID_TRAITEMENT_ROTATION          421
#define ID_TRAITEMENT_OPRATEURSUNAIRES_SEUILLAGEDEWEN 422
#define ID_TRAITEMENT_MORPHOLOGIE_EROSION 423
#define ID_TRAITEMENT_MORPHOLOGIE_DILATATION 424
#define ID_TRAITEMENT_MORPHOLOGIE_OUVERTURE 425
#define ID_TRAITEMENT_MORPHOLOGIE_FERMETURE 426
#define ID_OUTILS_PSEUDORELIEF          427
#define ID_TRANSFORMATION_CONVERSIONENBSPLINE 428
#define ID_TRAITEMENT_NORMALISATIONDESCOMPOSANTES 429
#define ID_PARZEN3D_MESUREDEVOLUMEDESCLASSES 430
#define ID_TRAITEMENT_MORPHOLOGIE_AMINCISSEMENT 433
#define ID_TRAITEMENT_MORPHOLOGIE_BARBULAGE 434
#define ID_TRAITEMENT_MORPHOLOGIE_EPAISSISSEMENT 435
#define ID_DCISION_DECISIONSURFLOAT     436
#define ID_DCISION_DECIDESURFLOATDEBUG  437
#define ID_DCISION_DECIDESVM            438
#define ID_DCISION_GENEREFICHIERDAT     439
#define ID_TRAITEMENT_COMPARAISONIMBIN  440
#define ID_TRAITEMENT_AJUSTEMENT        441
#define ID_TRAITEMENT_ANALYSECONTOUR    443
#define ID_TRAITEMENT_EQUILIBRAGE       444
#define ID_TEST_OUVRIR                  445
#define ID_DCISION_GENEREDATA           446
#define ID_TRAITEMENT_PETROU            447
#define ID_TRAITEMENT_CONTOURPETROU     448
#define ID_TRAITEMENT_CONVOLUTIONGAUSSIEN 450
#define ID_TRAITEMENT_CONVOLUTIONGAUSSIEN_GAUSSIEN1DX 451
#define ID_TRAITEMENT_CONVOLUTIONGAUSSIEN_GAUSSIEN1DY 452
#define ID_TRAITEMENT_CONVOLUTIONGAUSSIEN_CURVILINEARDETECTION 453
#define ID_TRAITEMENT_CURVILINEAR       454
#define ID_COLOR_CURVI                  455
#define ID_GRAD_Y                       456
#define ID_TRAITEMENT_ESTIMATIONTEMPSFFT 457
#define ID_TRAITEMENT_HYPERGRADIENT_PARBLOC 459
#define ID_TRAITEMENT_HYPERGRADIENT_FENETREGLISSANTE 460
#define ID_TRAITEMENT_HYPERGRADIENT_FENETREGLISSANTEZEROPADDING 461
#define ID_ZERNIKE_BATCHMOMENTS         462
#define ID_TRAITEMENT_OUTILS_ETUDEDISTANCEMAXI 463
#define ID_ETUDECURVI1D_GENERATIONFICHIERPROFIL_PORTE 464
#define ID_ETUDECURVI1D_ETUDEAVECOBJET_ETUDEPORTE 466
#define ID_ETUDECURVI1D_GENERATIONFICHIERPROFIL_PORTE32 467
#define ID_ETUDECURVI1D_GENERATIONFICHIERPROFIL_PORTE16 468
#define ID_ETUDECURVI1D_GENERATIONFICHIERPROFIL_PORTE12 469
#define ID_ETUDECURVI1D_ETUDEAVECOBJET_ETUDEPORTE32 470
#define ID_ETUDECURVI1D_ETUDEAVECOBJET_ETUDEPORTE16 473
#define ID_ETUDECURVI1D_ETUDEAVECOBJET_ETUDEPORTE12 474
#define ID_ETUDECURVI1D_ETUDEAVECOBJET_ETUDEPORTE12F4 475
#define ID_ETUDECURVI1D_GENERATIONFICHIERPROFIL_BITEXTURE48 476
#define ID_ETUDECURVI1D_ETUDEAVECOBJET_ETUDEBITEXTURE48 477
#define ID_ETUDECURVI1D_ETUDEAVECOBJET_ETUDEBITEXTURE48F4 478
#define ID_ETUDECURVI1D_GENERATIONFICHIERPROFIL_PORTEBORDNONSIM48 479
#define ID_ETUDECURVI1D_ETUDEAVECOBJET_ETUDEPORTENONSIM48F16 480
#define ID_ETUDECURVI1D_GENERATIONFICHIERPROFIL_MULTISIGNAUX1D 481
#define ID_ETUDECURVI1D_ETUDEAVECOBJET_ETUDESIGNAUXMULTIPLE48F16 482
#define ID_ETUDECURVI1D_ETUDEAVECOBJET_ETUDESIGNAUXRELS 483
#define ID_ETUDECURVI1D_ETUDEAVECOBJET_TESTNEW 484
#define ID_ETUDECURVI1D_ETUDEAVECOBJET_ETUDEMULTIFICHIER 485
#define ID_ETUDECURVI1D_STEGER          486
#define ID_STEGER_CONVOLUTION1D         487
#define ID_GENERATIONFICHIERPROFIL_OUTILS 488
#define ID_OUTILS_CONVERSION            489
#define ID_CONVERSION_SIGNAL            490
#define ID_CONVERSION_COUPE             491
#define ID_OUTILS_AJOUTBRUIT            492
#define ID_DETECTIONCURVILIN493         493
#define ID_OUTILS_SUIVIDECONTOURS       494
#define ID_OUTILS_PARAMCURVIDETECT      497
#define ID_TOOLS_MATCHING               498
#define ID_MATCHING_SELECTION3POINTS    499
#define ID_MATCHING_TRANSFORMATIONIMAGE 500
#define ID_TRANSFORMATIONIMAGE_PARAMTRANSFORMATION 501
#define ID_TRANSFORMATIONIMAGE_RUN      502
#define ID_MATCHING_CALCULMATRICEPASSAGE 503
#define ID_MATCHING_CALCULMATRICEPASSAGE504 504
#define ID_MATCHING_SELECTION4POINTS    505
#define ID_TRANSFORMATIONIMAGE_RUN506   506
#define ID_MATCHING_REPETABILIT507      507
#define ID_TRAITEMENT_PETROUCOULEUR     508
#define ID_TRAITEMENT_CURVICOULEUR      509
#define ID_TRAITEMENT_GAUSSIENCOULEUR   510
#define CG_IDC_PROGDLG_PROGRESS         1003
#define CG_IDC_PROGDLG_PERCENT          1004
#define IDC_i1                          1008
#define IDC_SEUIL                       1008
#define IDC_i2                          1009
#define IDC_NBIMAGE                     1009
#define IDC_SEUIL2                      1009
#define IDC_j2                          1010
#define IDC_TEMPS                       1010
#define IDC_NUM1                        1010
#define IDC_SEUIL1                      1010
#define IDC_CHECK                       1010
#define IDC_j1                          1011
#define IDC_NUM2                        1011
#define IDC_LIST1                       1015
#define IDC_LIST2                       1016
#define IDC_AJOUTER                     1018
#define IDC_LARG                        1019
#define IDC_ENLEVER                     1019
#define IDC_TITRE                       1020
#define IDC_FichProj                    1020
#define IDC_HAUT                        1021
#define IDC_IMACL0                      1021
#define IDC_FICHPOLYDEC                 1021
#define IDC_NB                          1022
#define IDC_RECOUVR0                    1022
#define IDC_IMACL1                      1022
#define IDC_COLOR                       1023
#define IDC_EDIT1                       1023
#define IDC_RECOUVR1                    1023
#define IDC_FICHPOLY                    1023
#define IDC_SCROLLSEUIL                 1024
#define IDC_EDIT3                       1024
#define IDC_EDIT_IMAGE_2                1024
#define IDC_FICHMES                     1024
#define IDC_TETA                        1024
#define IDC_EDIT4                       1025
#define IDC_Nom_Traitement              1025
#define IDC_REPONSE                     1025
#define IDC_PARAM0                      1025
#define IDC_EDIT5                       1026
#define IDC_COMMENT_TRAITEMENT          1026
#define IDC_PARAM1                      1026
#define IDC_EDIT_MINA                   1028
#define IDC_EDIT_MAXA                   1029
#define IDC_EDIT_AMIN_SEUIL             1029
#define IDC_EDIT_MINB                   1030
#define IDC_EDIT_MAXB                   1031
#define IDC_EDIT_IMAGE_1                1031
#define IDC_EDIT_PASA                   1032
#define IDC_BUTTON1                     1032
#define IDC_EDIT_PASB                   1033
#define IDC_BUTTON2                     1033
#define IDC_AJOUTERFICH                 1034
#define IDC_EDIT_FACTEUR_ZOOM           1036
#define IDC_TEXT                        1036
#define IDC_NOMPROJET                   1037
#define IDC_NOMIMAGEAPPR                1038
#define IDC_TAILLE                      1038
#define IDC_NOMFICHIERAPPR              1039
#define IDC_COMBO1                      1040
#define IDC_NOMFICHIERPARAM             1040
#define IDC_TREE1                       1041
#define IDC_COMBO2                      1042
#define IDC_NOMMMC                      1043
#define IDC_AJOUTERCLAS                 1044
#define IDC_SUPPRIMCLAS                 1045
#define IDC_CHECK1                      1047
#define IDC_EDIT2                       1047
#define IDC_SPIN2                       1048
#define IDC_CHECK_REG                   1048
#define IDC_SPIN1                       1049
#define IDC_BUTTON3                     1050
#define IDC_SLIDER1                     1051
#define IDC_EDITCTRL1                   1055
#define IDC_EDIT_TE                     1060
#define IDC_X0                          1061
#define IDC_EDIT_DW                     1061
#define IDC_FOCALE                      1062
#define IDC_EDIT_ML                     1062
#define IDC_DISTANCE                    1063
#define IDC_EDIT_MW                     1063
#define IDC_EDIT_ML2                    1064
#define IDC_TXTMAXW                     1065
#define IDC_EDIT_REG                    1066
#define IDC_TXTMAXW2                    1067
#define IDC_EDIT_TAILLECOUPE            1067
#define IDC_STATIC_LARGEUR              1068
#define IDC_VALLARGEUR                  1069
#define IDC_SLIDERLARGEUR               1070
#define IDC_STATICM1                    1071
#define IDC_EDITM1                      1072
#define IDC_EDITM2                      1073
#define IDC_PROGRESSCURVI               1073
#define IDC_STATIC_LARGEURFOURIER       1074
#define IDC_STATICM2                    1074
#define IDC_STATIC_Petrou               1074
#define IDC_SLIDERLARGEURFOURIER        1075
#define IDC_EDITM3                      1075
#define IDC_STATIC_Tracking             1075
#define IDC_VALLARGEURFOURIER           1076
#define IDC_STATICM3                    1076
#define IDC_STATIC_1DProcess            1076
#define IDC_STATIC_LARGEURMINI          1077
#define IDC_EDITM4                      1077
#define IDC_STATIC_2DProcess            1077
#define IDC_SLIDERLARGEURMINI           1078
#define IDC_STATICM4                    1078
#define IDC_STATIC_Display              1078
#define IDC_VALLARGEURMINI              1079
#define IDC_EDITM5                      1079
#define IDC_STATIC_POURCENTAGE          1079
#define IDC_STATIC_NBLISTE              1080
#define IDC_STATICM5                    1080
#define IDC_SLIDERNBLIST                1081
#define IDC_VALLARGEURNBLIST            1082
#define IDC_STATIC_SeuilReponse         1083
#define IDC_EDITM6                      1083
#define IDC_SLIDERSEUILREPONSE          1084
#define IDC_STATICM6                    1084
#define IDC_VALSEUILREPONSE             1085
#define IDC_EDITM7                      1085
#define IDC_STATIC_LARGEURMINI2         1086
#define IDC_STATICM7                    1086
#define IDC_SLIDERVARIATIONLOCALELARGEUR 1087
#define IDC_VARIATIONLOCALELARGEUR      1088
#define IDC_CHECK2                      1089
#define IDC_CHECK3                      1090
#define IDC_CHECKDEBUGCONTOURS          1091
#define IDC_NBREG                       1092
#define ID_VPS_CH_EXT_THRESHOLD         32790
#define ID_VPS_MAXI_VISU                32791
#define ID_VPS_GRADIENT_VISU            32792
#define ID_VPS_CH_CONTIY_THR            32793
#define ID_VPS_CONTIY_FILTER            32794
#define ID_VPS_LEVEL_CURVES_VISU        32795
#define ID_VPS_WHEELS_AXIS              32825
#define ID_VPS_GRAD_ALONGX              32827
#define ID_VPS_GRAD_ALONGY              32828
#define ID_VPS_DETECT_FORM              32834
#define CG_IDS_PROGRESS_CAPTION         57638

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        210
#define _APS_NEXT_COMMAND_VALUE         511
#define _APS_NEXT_CONTROL_VALUE         1093
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
